
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include <page_layout_reader_lexer.h>

using namespace TB_READER_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD PAGE_LAYOUT_READER_LEXER::keywords[] = {
    TOKDEF( bitmap ),
    TOKDEF( bold ),
    TOKDEF( bottom ),
    TOKDEF( bottom_margin ),
    TOKDEF( center ),
    TOKDEF( comment ),
    TOKDEF( data ),
    TOKDEF( end ),
    TOKDEF( font ),
    TOKDEF( incrlabel ),
    TOKDEF( incrx ),
    TOKDEF( incry ),
    TOKDEF( italic ),
    TOKDEF( justify ),
    TOKDEF( lbcorner ),
    TOKDEF( left ),
    TOKDEF( left_margin ),
    TOKDEF( line ),
    TOKDEF( linewidth ),
    TOKDEF( ltcorner ),
    TOKDEF( maxheight ),
    TOKDEF( maxlen ),
    TOKDEF( name ),
    TOKDEF( notonpage1 ),
    TOKDEF( option ),
    TOKDEF( page1only ),
    TOKDEF( page_layout ),
    TOKDEF( pngdata ),
    TOKDEF( polygon ),
    TOKDEF( pos ),
    TOKDEF( pts ),
    TOKDEF( rbcorner ),
    TOKDEF( rect ),
    TOKDEF( repeat ),
    TOKDEF( right ),
    TOKDEF( right_margin ),
    TOKDEF( rotate ),
    TOKDEF( rtcorner ),
    TOKDEF( scale ),
    TOKDEF( setup ),
    TOKDEF( size ),
    TOKDEF( start ),
    TOKDEF( tbtext ),
    TOKDEF( textlinewidth ),
    TOKDEF( textsize ),
    TOKDEF( top ),
    TOKDEF( top_margin ),
    TOKDEF( xy )
};

const unsigned PAGE_LAYOUT_READER_LEXER::keyword_count = unsigned( sizeof( PAGE_LAYOUT_READER_LEXER::keywords )/sizeof( PAGE_LAYOUT_READER_LEXER::keywords[0] ) );


const char* PAGE_LAYOUT_READER_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}
